### PR TITLE
Adding Web HMI. Lightweight Flask webserver that runs on X1Plus itself.

### PR DESCRIPTION
**Pull request by christophergault198**
Working flask web HMI for X1Plus. Served on port: `5001`. Currently returns current toolhead and FLC images with multiple printer commands and currently working on a ML model with scooterthedev. Yes, `dark mode' is included. @jphannifan @riptidewave93
image

### CODE REVIEW

**Comment by christophergault198** [comment]
Build did not append any of the folders as expected including `/images/cfw/etc/init.d/S98webhmi` ,`/images/cfw/usr/etc/system/webhmi` folder. Also missing venv folder from build, need to include.

**Comment by scooterthedev** [comment]
I believe it should be pushed when we have a finished product, so we are not putting in a pr everytime we add a small feature. It hasn't been fully tested yet on device, and I'm worried that it's not going to work as expected when it's pushed to 1.2. Lets take some more time to finalize everything, and make sure that there are no bugs, or anything that would conflict other stuff from working ie. running out of RAM, using a port that's is meant to be used for something else etc. @christophergault198

**Comment by christophergault198** [comment]
> I believe it should be pushed when we have a finished product, so we are not putting in a pr everytime we add a small feature. It hasn't been fully tested yet on device, and I'm worried that it's not going to work as expected when it's pushed to 1.2. Lets take some more time to finalize everything, and make sure that there are no bugs, or anything that would conflict other stuff from working ie. running out of RAM, using a port that's is meant to be used for something else etc. @christophergault198

Noted, mainly intended to bring awareness outside. This is why build has not been reported. Will use more appropriate channels.

**Comment by christophergault198** [comment]
Looking for broader ideas here. Otherwise should Close?

**Comment by christophergault198** [comment]
Closing due to needed improvements and review.

**Pull request closed without merging**
