### PR TITLE
Add initial translations for Russian and Japanese

### PR DESCRIPTION
**Pull request by jwise**
Thanks to Henry Thomasino (@ecycorin) and Jun (@jun_270) for their hard work on translations!

### CODE REVIEW

**Review by riptidewave93 — APPROVED** [review]

**Comment by jphannifan** [comment]
@jwise if we add the .qm files to the root.qrc of kexec_ui, then kexec_ui loads in whatever language is saved in printer.json

otherwise kexec_ui doesn't translate into any other languages

**Comment by jwise** [comment]
Yeah, I'll do that in a separate PR.

**Comment by Ben-PH** [comment]
Слава Україні!

**Comment by jwise** [comment]
An off-topic comment has been removed from this pull request.  (This removal does not express an opinion on the contents of the removed comment, but only whether it is appropriate for this space.)

**Pull request merged**
