### PR TITLE
Add a Klipperscreen-style temperature graph option.

### PR DESCRIPTION
**Pull request by jwise**
Adds a temperature graph to the home screen, configurable with the `homescreen.graph.enabled` setting.  Time scale is logarithmic, with much more visual precision available in the most recent minute, transitioning to a 5-minute or 15-minute trendline.

image

Future work would be to also plot fan speeds, print events, average feed rates, etc; for now, this is fixed function of nozzle / bed / chamber temp.

Associated with #30, but there still needs to be UI work done to build a toggle for this before we can close that.

### CODE REVIEW

**Review by bani6809 — APPROVED** [review]
appears to work. approved

**Comment by jphannifan** [comment]
Fan speed properties work identically to the heater properties. We just need a way to toggle different plot elements.
```
PrintManager.fans.cooling.fanSpeed
PrintManager.fans.auxiliary.fanSpeed
PrintManager.fans.chamber.fanSpeed
```

And whenever the print speed stuff is PRed that can be another plot option

**Comment by bani6809** [comment]
how do i turn it off?

./x1plus-test-settings.py homescreen.graph.enabled=0

and

./x1plus-test-settings.py homescreen.graph.enabled=false

both have no effect, it remains on even after reboot

**Comment by jphannifan** [comment]
> how do i turn it off?
> 
> ./x1plus-test-settings.py homescreen.graph.enabled=0
> 
> and
> 
> ./x1plus-test-settings.py homescreen.graph.enabled=false
> 
> both have no effect, it remains on even after reboot

you might have to check logs and/or dbus logs to explain that one

**Comment by jwise** [comment]
`./x1plus-test-settings.py homescreen.graph.enabled=None`

turns it off.  this is an artifact of x1plus-test-settings being weird, we will come back to this when this actually becomes a real CLI tool

**Comment by jwise** [comment]
> Fan speed properties work identically to the heater properties. We just need a way to toggle different plot elements.
> 
> ```
> PrintManager.fans.cooling.fanSpeed
> PrintManager.fans.auxiliary.fanSpeed
> PrintManager.fans.chamber.fanSpeed
> ```
> 
> And whenever the print speed stuff is PRed that can be another plot option

I agree.  future work!

also it might be nice to have feed rates or something?

**Comment by jphannifan** [comment]
We should get a toggle button here.. a simple icon like this should work 
image

**Comment by RaySajuuk** [comment]
Home Screen shows blank when start any print job with this PR.
IMG_3772

**Comment by jwise** [comment]
@RaySajuuk Oof.  Did you explicitly turn on the graph?  Or is this with default settings?

**Comment by jwise** [comment]
> We don't have feed rate data for this last I checked. That's all set by gcode

we can get effective feed rate data by number of meters of filament printed, though, right?  I wonder how often that is updated

**Comment by jphannifan** [comment]
@RaySajuuk Interesting. Do you have log output you can share? I'm having trouble getting the plot to display while a print is running, but I don't have this visual display error you see. My log output is not giving me much insight. 

Are you able to use the rest of the menu without any issues?

**Comment by jphannifan** [comment]
> > We don't have feed rate data for this last I checked. That's all set by gcode
> 
> we can get effective feed rate data by number of meters of filament printed, though, right? I wonder how often that is updated

I don't know if the info from /config/ is updated mid-print but it'd be worth checking. Now that you mention it though, I believe we have access to some form of real time usage data for RFID-tagged spools. It's not true odometry so we'd have to experiment. 

One thing we can plot for sure is print speed. I was going to test that out at some point. Fan speed looks great when plotted alongside temperatures. The disappointing thing though is we can't read the exact fan speeds. 

I have an idea for layer count and print state. I'll get a branch ready and tag you

**Comment by RaySajuuk** [comment]
> @RaySajuuk Oof. Did you explicitly turn on the graph? Or is this with default settings?

default settings, did not explicitly turn on the graph.

**Comment by RaySajuuk** [comment]
> @RaySajuuk Interesting. Do you have log output you can share? I'm having trouble getting the plot to display while a print is running, but I don't have this visual display error you see. My log output is not giving me much insight.
> 
> Are you able to use the rest of the menu without any issues?

I have reverted back to the previous commit. Forgot to save logs, reformatted my SD card, as part of troubleshoot steps.

**Comment by jphannifan** [comment]
> > @RaySajuuk Oof. Did you explicitly turn on the graph? Or is this with default settings?
> 
> default settings, did not explicitly turn on the graph. I actually tried reclone the repo and rebuild the image, also reset the printer. then reinstalled it, without any changes, issue persisted.

There are some significant changes behind the scenes since 1.1. One of those is migrating user settings to a newer and better service. There's also a base firmware update on top of that, and many other changes that we are still working out some bugs. For now I'd recommend using https://github.com/X1Plus/X1Plus/commit/fad43697732b04314c8d5d4f3e77379b973d5f36 and in a few days we should have things running smoothly.

**Comment by RaySajuuk** [comment]
> > > @RaySajuuk Oof. Did you explicitly turn on the graph? Or is this with default settings?
> > 
> > 
> > default settings, did not explicitly turn on the graph. I actually tried reclone the repo and rebuild the image, also reset the printer. then reinstalled it, without any changes, issue persisted.
> 
> There are some significant changes behind the scenes since 1.1. One of those is migrating user settings to a newer and better service. There's also a base firmware update on top of that, and many other changes that we are still working out some bugs. For now I'd recommend using [fad4369](https://github.com/X1Plus/X1Plus/commit/fad43697732b04314c8d5d4f3e77379b973d5f36) and in a few days we should have things running smoothly.
> 
> (the graph being enabled by default is one of these bugs)

My apologies, scrolled up the thread and saw it just now. 🫠

**Comment by jphannifan** [comment]
> > > > @RaySajuuk Oof. Did you explicitly turn on the graph? Or is this with default settings?
> > > 
> > > 
> > > default settings, did not explicitly turn on the graph. I actually tried reclone the repo and rebuild the image, also reset the printer. then reinstalled it, without any changes, issue persisted.
> > 
> > 
> > There are some significant changes behind the scenes since 1.1. One of those is migrating user settings to a newer and better service. There's also a base firmware update on top of that, and many other changes that we are still working out some bugs. For now I'd recommend using [fad4369](https://github.com/X1Plus/X1Plus/commit/fad43697732b04314c8d5d4f3e77379b973d5f36) and in a few days we should have things running smoothly.
> > (the graph being enabled by default is one of these bugs)
> 
> My apologies, scrolled up the thread and saw it just now. 🫠

No apologies needed! You are more than welcome to test any build you find on here, but with any that are not marked as an official release, it's easy to run into bugs and that can really be a pain when you need to start a print :)

**Comment by RaySajuuk** [comment]
> > > > > @RaySajuuk Oof. Did you explicitly turn on the graph? Or is this with default settings?
> > > > 
> > > > 
> > > > default settings, did not explicitly turn on the graph. I actually tried reclone the repo and rebuild the image, also reset the printer. then reinstalled it, without any changes, issue persisted.
> > > 
> > > 
> > > There are some significant changes behind the scenes since 1.1. One of those is migrating user settings to a newer and better service. There's also a base firmware update on top of that, and many other changes that we are still working out some bugs. For now I'd recommend using [fad4369](https://github.com/X1Plus/X1Plus/commit/fad43697732b04314c8d5d4f3e77379b973d5f36) and in a few days we should have things running smoothly.
> > > (the graph being enabled by default is one of these bugs)
> > 
> > 
> > My apologies, scrolled up the thread and saw it just now. 🫠
> 
> No apologies needed! You are more than welcome to test any build you find on here, but with any that are not marked as an official release, documentation is usually scarce and although we try to solve any bugs before merging, a few always slip through the cracks. The info you provided was useful, so thank you

Good, I am glad you find the info useful.

**Pull request merged**
