### PR TITLE
Added sudo for x1p building

### PR DESCRIPTION
**Pull request by scooterthedev**
This is more of a useless addition, but it's nice to be able to just copy and paste. In the compiling section, there is no sudo for the commands, and if ran by someone, it will throw an error. Pretty much for lazy people (like me), who just wants to copy and paste.

### CODE REVIEW

**Comment by RaySajuuk** [comment]
The build commands are LGTM and works fine.

If your environment requires special configuration then it should be only limited to you. 

If you done post installation correctly, there is no need to add sudo.

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by jphannifan** [comment]
> 
> The build commands are LGTM and works fine.
> 
> If your environment requires special configuration then it should be only limited to you. 
> 
> If you done post installation correctly, there is no need to add sudo.
> 
> https://docs.docker.com/engine/install/linux-postinstall/

Yep the only time I use sudo with docker is if something isn't quite configured right. 

Things like pulling a repo on Windows and then trying to run the dockerfile from WSL2 can cause permission errors that in most cases it's just better to rebuild the image from scratch

**Comment by jwise** [comment]
Yeah, I don't think we should be having people sudo to run docker, but I wouldn't object to having a sentence in there that says 'if you need to sudo, make sure you're in the docker group on your system' or something

**Comment by RaySajuuk** [comment]
> Yeah, I don't think we should be having people sudo to run docker, but I wouldn't object to having a sentence in there that says 'if you need to sudo, make sure you're in the docker group on your system' or something

Maybe a FAQ section for some common platform configurations, like on Mac I will need `-u 0` and `--platform linux/amd64` to work.  We can add the Docker KB link for post installation.

**Comment by scooterthedev** [comment]
> 
> The build commands are LGTM and works fine.
> 
> If your environment requires special configuration then it should be only limited to you. 
> 
> If you done post installation correctly, there is no need to add sudo.
> 
> https://docs.docker.com/engine/install/linux-postinstall/

Yah, thanks. Totally forgot about this as I haven't used docker in some time. I will close this pr unless otherwise needed.

**Comment by jphannifan** [comment]
> > The build commands are LGTM and works fine.
> > If your environment requires special configuration then it should be only limited to you.
> > If you done post installation correctly, there is no need to add sudo.
> > https://docs.docker.com/engine/install/linux-postinstall/
> 
> Yah, thanks. Totally forgot about this as I haven't used docker in some time. I will close this pr unless otherwise needed.

Could you test if the updated docker instructions work for you on Windows? https://github.com/X1Plus/X1Plus/pull/280/files

I would but I'm traveling atm and all I have is a Macbook.

**Comment by scooterthedev** [comment]
Yah, I will try test them soon. I usually use Linux for this, but I also have a Windows device I'll test it on.

**Comment by jphannifan** [comment]
Oh for some reason I thought you were on Windows. No worries if it's not convenient. I can test it tomorrow 
It should work as long as WSL is running first.

**Comment by scooterthedev** [comment]
> Oh for some reason I thought you were on Windows. No worries if it's not convenient. I can test it tomorrow It should work as long as WSL is running first.

I will test it right now. I use both Linux and Windows as my primary devices, lol.

**Comment by scooterthedev** [comment]
> @scooterthedev Could you test if the updated docker instructions work for you on Windows? https://github.com/X1Plus/X1Plus/pull/280/files

So I tested it, and it seemed to go well besides for when I get to the code ` docker exec -v` and onwards. I seem to get this error  `unknown shorthand flag: 'v' in -v
See 'docker exec --help'`. I'm not sure if this is just a WSL issue, as it works fine on my linux machine. Besides for that I will just change some stuff up to be nitpicky. If you could look into this before we push, that would be good. I couldn't really find anything online about this, but I'll keep looking.

**Comment by scooterthedev** [comment]
I'm going to close this pr, as the main pr is #280, and no this one. Any subsequent conversations regrading the docker scripts can run on that pr over this one, so we won't have to jump back and forth between pr's.

**Pull request closed without merging**
